[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "GPT_from_scratch"
version = "0.0.0"
requires-python = ">= 3.10"

[tool.setuptools]
packages = ["src"]


